/*
-- Query: SELECT * FROM demande_creation_article.wa_sous_famille
LIMIT 0, 50000

-- Date: 2016-11-09 10:28
*/
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (1,'497','ABRIS JARDINS ET GARAGES - 497',0,14,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (2,'298','ACC BOIS RECONSTITUÉ FINI - 298',0,8,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (3,'476','ACCES. TERRASSES RX-GSB - 476',0,14,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (4,'488','ACCES.CLOTURES COMPOSITES - 488',0,14,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (5,'490','ACCES.CLOTURES RESINEUX - 490',0,14,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (6,'486','ACCES.ECRAN RESINEUX - 486',0,14,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (7,'468','ACCES.TERRASSE COMPO. GSB - 468',0,14,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (8,'481','ACCES.TERRASSE COMPOSITES - 481',0,14,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (9,'406','ACCES.TERRASSE EXOTIQUE - 406',0,14,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (10,'482','ACCES.TERRASSE RESINEUX - 482',0,14,8);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (11,'478','ACCES.TERRASSES RX FINIES - 478',0,14,9);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (12,'507','ACCESOIRES ESCALIERS - 507',0,1,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (13,'499','ACCESS.JEUX EXTERIEURS - 499',0,14,10);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (14,'339','ACCESSOIRE LAMBRIS DETAIL - 339',0,21,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (15,'290','ACCESSOIRES BARDAGES BRUT - 290',0,8,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (16,'292','ACCESSOIRES BARDAGES FINI - 292',0,8,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (17,'374','ACCESSOIRES BOIS PLACO - 374',0,40,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (18,'265','ACCESSOIRES ITE - 265',0,8,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (19,'311','ACCESSOIRES LAMBRIS BRUTS - 311',0,20,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (20,'338','ACCESSOIRES LAMBRIS FINIS - 338',0,20,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (21,'224','B. MASSIF RAB PIN HORS 45 - 224',0,7,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (22,'397','BAGNERES BOIS - 397',0,34,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (23,'289','BARDAGE BOIS RECONSTITUE - 289',0,8,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (24,'303','BARDAGE EXTRA GD CHANTIER - 303',0,8,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (25,'279','BARDAGE FINI SYST ANTI UV - 279',0,8,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (26,'261','BARDAGE GSB-NORDIC SATURE - 261',0,8,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (27,'304','BARDAGE NATUR GD CHANTIER - 304',0,8,8);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (28,'263','BARDAGE PROTECT - 263',0,8,9);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (29,'276','BARDAGES BISEAU COULEUR - 276',0,8,10);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (30,'269','BARDAGES BRUTS PROMO - 269',0,8,11);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (31,'264','BARDAGES CHOIX B COULEUR - 264',0,8,12);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (32,'272','BARDAGES CLASSIC - 272',0,8,13);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (33,'273','BARDAGES ESSENCE - 273',0,8,14);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (34,'287','BARDAGES ESSENCE HUILÉ - 287',0,8,15);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (35,'284','BARDAGES EXTRA - 284',0,8,16);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (36,'299','BARDAGES FINIS MDD - 299',0,8,17);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (37,'301','BARDAGES GSB BRUTS PROMO - 301',0,8,18);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (38,'295','BARDAGES GSB-BASIC - 295',0,8,19);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (39,'267','BARDAGES GSB-COUL./MESURE - 267',0,8,20);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (40,'278','BARDAGES GSB-NORDIC - 278',0,8,21);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (41,'296','BARDAGES GSB-ORIGINEL - 296',0,8,22);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (42,'266','BARDAGES LINE COULEUR - 266',0,8,23);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (43,'277','BARDAGES METAL - 277',0,8,24);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (44,'286','BARDAGES NATUR - 286',0,8,25);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (45,'294','BARDAGES NORDICLIN HUILE - 294',0,8,26);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (46,'285','BARDAGES NORDICOLOR - 285',0,8,27);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (47,'297','BARDAGES PROFILS SPECIAUX - 297',0,8,28);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (48,'274','BARDAGES SEMI TRANSFORMES - 274',0,8,29);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (49,'275','BARDAGES SILVER LAB COUL. - 275',0,8,30);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (50,'356','BARRES VOLETS - 356',0,3,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (51,'357','BARRES VOLETS DETAIL - 357',0,4,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (52,'245','BASTAING CALIBRÉ - 245',0,7,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (53,'222','BMA RABOTES - HORS 45 MM - 222',0,7,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (54,'210','BOIS BRUTS RX DETAILS - 210',0,6,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (55,'221','BOIS CONTRECOLLES - 221',0,7,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (56,'230','BOIS FERMETTES CALIBRES - 230',0,7,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (57,'231','BOIS FERMETTES CALIBRES I - 231',0,7,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (58,'220','BOIS LAMELLE COLLE - 220',0,7,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (59,'236','BOIS MASSIFS RAB. HORS 45 - 236',0,7,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (60,'234','BOIS OSSATURE - 234',0,7,8);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (61,'235','BOIS OSSATURE I - 235',0,7,9);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (62,'410','BOIS RABOTÉS INDUSTRIELS - 410',0,34,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (63,'228','BOIS STRUCTURE IMPORT - 228',0,7,10);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (64,'401','CAILLEBOTIS DETAIL - 401',0,15,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (65,'241','CHANLATTE - 241',0,7,11);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (66,'244','CHEVRONS - 244',0,7,12);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (67,'508','CHUTES A L\'UNITE - 508',0,1,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (68,'509','CHUTES AU M3 - 509',0,1,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (69,'515','CIRE - 515',0,16,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (70,'282','CLINS AUT.LASUR.(ARCHIVE) - 282',0,8,31);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (71,'270','CLINS BRUTS (ARCHIVES) - 270',0,8,32);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (72,'271','CLINS BRUTS DETAIL - 271',0,9,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (73,'280','CLINS EXTRA - 280',0,8,33);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (74,'281','CLINS EXTRA DÉTAIL - 281',0,9,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (75,'283','CLINS NATUR - 283',0,8,34);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (76,'489','CLOTURES BRUTES RESINEUX - 489',0,14,11);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (77,'479','CLOTURES BRUTES RX MDD - 479',0,14,12);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (78,'477','CLOTURES BRUTES RX-GSB - 477',0,14,13);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (79,'487','CLOTURES COMPOSITES - 487',0,14,14);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (80,'492','CLOTURES FINIES RESINEUX - 492',0,14,15);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (81,'503','CLOTURES RX FINIES - GSB - 503',0,14,16);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (82,'259','COMPOSANTS INDUSTRIELS - 259',0,7,13);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (83,'535','CONSOMMABLES - 535',0,10,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (84,'512','CONSOMMABLES - 512',0,16,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (85,'495','CONTENANTS BRUTS - 495',0,14,17);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (86,'496','CONTENANTS FINIS - 496',0,14,18);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (87,'500','COPEAUX ET SCIURES - 500',0,11,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (88,'577','CP - 577',0,38,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (89,'574','CP DECO - 574',0,37,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (90,'576','CP DETAIL - 576',0,37,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (91,'594','ECHANTILLONS A LA DEMANDE - 594',0,12,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (92,'593','ECHANTILLONS AMENAG.EXTER - 593',0,12,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (93,'590','ECHANTILLONS BARDAGES - 590',0,12,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (94,'597','ECHANTILLONS GSB AMEX - 597',0,12,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (95,'598','ECHANTILLONS GSB AUTRES R - 598',0,12,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (96,'595','ECHANTILLONS GSB BARDAGES - 595',0,12,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (97,'596','ECHANTILLONS GSB LAMBRIS - 596',0,12,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (98,'599','ECHANTILLONS GSB SUR DDE - 599',0,12,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (99,'591','ECHANTILLONS LAMBRIS - 591',0,12,8);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (100,'592','ECHANTILLONS STRUCTURE - 592',0,12,9);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (101,'521','ECO MOBILIER - 521',0,13,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (102,'493','ECRANS FINIS RESINEUX - 493',0,14,19);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (103,'469','ECRANS FINIS RESINEUX GSB - 469',0,14,20);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (104,'485','ECRANS RESINEUX - 485',0,14,21);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (105,'252','ENCOURS DE SCIAGE - 252',0,7,14);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (106,'506','ESCALIERS - 506',0,1,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (107,'519','ESCOMPTE - 519',0,16,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (108,'510','FOURNITURES ET ART.DIVERS - 510',0,16,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (109,'518','FRAIS DE FACTURATION - 518',0,16,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (110,'580','GRANULES BOIS - 580',0,5,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (111,'200','HORS STANDARD FAB A CDE - 200',0,17,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (112,'498','JEUX EXTERIEURS - 498',0,14,22);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (113,'225','KIT PLANCHER POUTRES EN I - 225',0,18,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (114,'226','KIT PORTIQUE LAMELLE COLL - 226',0,18,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (115,'227','KIT PORTIQUE LAMIBOIS - 227',0,18,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (116,'359','KITS PLANCHER - 359',0,26,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (117,'550','LAINES DE VERRES - 550',0,19,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (118,'315','LAMB.BRUT PROFIL SPECIAUX - 315',0,20,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (119,'314','LAMB.BRUTS GSB-MDD - 314',0,20,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (120,'313','LAMB.GSB BASICS NATURELS - 313',0,20,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (121,'262','LAMBOURDES BOIS RESINEUX - 262',0,7,15);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (122,'329','LAMBRIS A PERSONNALISER - 329',0,20,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (123,'316','LAMBRIS AU NATUREL - 316',0,20,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (124,'322','LAMBRIS AUTRES LASURÉS - 322',0,20,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (125,'330','LAMBRIS BELOUGA - 330',0,20,8);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (126,'331','LAMBRIS BELOUGA DÉTAIL - 331',0,21,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (127,'328','LAMBRIS CLASSIC BLANC - 328',0,20,9);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (128,'310','LAMBRIS CLASSIC NATUREL - 310',0,20,10);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (129,'332','LAMBRIS CLASSIC VERNIS - 332',0,20,11);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (130,'344','LAMBRIS COULEURS D\'ICI - 344',0,20,12);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (131,'367','LAMBRIS FINIS GSB NEW MDD - 367',0,20,13);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (132,'309','LAMBRIS FINIS GSB-MDD - 309',0,20,14);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (133,'320','LAMBRIS GRIZZLI - 320',0,20,15);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (134,'321','LAMBRIS GRIZZLI DÉTAIL - 321',0,21,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (135,'308','LAMBRIS GSB BASIC BLANC - 308',0,20,16);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (136,'307','LAMBRIS GSB BRUTS PROMO - 307',0,20,17);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (137,'325','LAMBRIS GSB ELEGANCE - 325',0,20,18);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (138,'324','LAMBRIS GSB ESSENTIEL - 324',0,20,19);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (139,'306','LAMBRIS GSB FINIS PROMO - 306',0,20,20);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (140,'362','LAMBRIS GSB LAMELLE COLLE - 362',0,20,21);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (141,'366','LAMBRIS GSB NEW BLANCS - 366',0,20,22);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (142,'364','LAMBRIS GSB NEW BRUNS - 364',0,20,23);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (143,'363','LAMBRIS GSB NEW GRIS - 363',0,20,24);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (144,'365','LAMBRIS GSB NEW VIELLIS - 365',0,20,25);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (145,'336','LAMBRIS GSB PREPEINT - 336',0,20,26);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (146,'327','LAMBRIS GSB REFLETS - 327',0,20,27);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (147,'326','LAMBRIS GSB TONIC - 326',0,20,28);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (148,'319','LAMBRIS HAPPY COLORS - 319',0,20,29);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (149,'335','LAMBRIS KOALA - 335',0,20,30);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (150,'318','LAMBRIS METAL - 318',0,20,31);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (151,'334','LAMBRIS NORDICHOME - 334',0,20,32);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (152,'337','LAMBRIS O\'NEY - 337',0,20,33);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (153,'349','LAMBRIS ORIGINELS BLANCS - 349',0,20,34);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (154,'341','LAMBRIS ORIGINELS BRUNS - 341',0,20,35);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (155,'348','LAMBRIS ORIGINELS GRIS - 348',0,20,36);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (156,'346','LAMBRIS SELECT - 346',0,20,37);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (157,'312','LAMBRIS SEMIS TRANSFORMES - 312',0,20,38);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (158,'368','LAMBRIS SILVER LAB COUL. - 368',0,20,39);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (159,'317','LAMBRIS SO CHIC - 317',0,20,40);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (160,'343','LAMBRIS VINTAGE - 343',0,20,41);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (161,'354','LAMES VOLETS - 354',0,23,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (162,'355','LAMES VOLETS DETAIL - 355',0,22,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (163,'353','LAMES VOLETS GSB-MDD - 353',0,23,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (164,'199','LITEAUX - 199',0,7,16);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (165,'240','LITEAUX - 240',0,7,17);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (166,'239','LITEAUX I - 239',0,7,18);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (167,'412','MAT.1ÈRES CERLAND - 412',0,34,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (168,'390','MOULURES BRUTES - 390',0,24,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (169,'398','MOULURES BRUTES PAQUET - 398',0,25,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (170,'391','MOULURES BRUTES/BOTTE - 391',0,24,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (171,'395','MOULURES FINIES - 395',0,24,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (172,'258','NAIL WEB FOURNITURES - 258',0,30,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (173,'232','OSSATURE ABOUTÉE - NON CE - 232',0,7,19);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (174,'223','OSSATURE ABOUTEE 45 MM - 223',0,7,20);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (175,'233','OSSATURE MASSIVE 45 MM - 233',0,7,21);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (176,'572','PANNEAU AGGLO-OSB-FIBRE - 572',0,37,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (177,'578','PANNEAU ISOREL (ARCHIVE) - 578',0,37,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (178,'573','PANNEAUX AGGLO-OSB-FIBRE - 573',0,38,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (179,'351','PARQUETS NATURELS - 351',0,26,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (180,'475','PDTS SPÉCIAUX AMEX GSB - 475',0,14,23);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (181,'516','PEINTURE - 516',0,16,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (182,'494','PERGOLAS - 494',0,14,24);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (183,'350','PLANCHERS BRUTS - 350',0,26,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (184,'358','PLANCHERS GSB SPEC. PROMO - 358',0,26,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (185,'352','PLANCHERS VERNIS - 352',0,26,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (186,'197','PLANCHES AGRICOLE - 197',0,7,22);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (187,'254','PLANCHES AGRICOLE - 254',0,7,23);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (188,'255','PLANCHES AGRICOLE I - 255',0,7,24);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (189,'300','PLANCHES DE RIVE BRUTES - 300',0,2,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (190,'302','PLANCHES DE RIVE PEINTES - 302',0,2,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (191,'345','PLINTH.BRUTES AU DÉTAIL - 345',0,28,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (192,'347','PLINTH.PRE-PEINTES DÉTAIL - 347',0,28,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (193,'340','PLINTHES BRUTES - 340',0,27,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (194,'361','PLINTHES BRUTES PROMO - 361',0,27,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (195,'342','PLINTHES PRE-PEINTES - 342',0,27,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (196,'403','POTEAUX DETAIL - 403',0,15,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (197,'402','POTEAUX RESINEUX - 402',0,14,25);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (198,'466','POTEAUX RESINEUX GSB - 466',0,14,26);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (199,'504','POUTRE CHENE - 504',0,1,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (200,'253','POUTRELLES COFFRAGES - 253',0,29,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (201,'257','POUTRELLES LVL-LAMIBOIS - 257',0,29,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (202,'360','POUTRES À CHALET BRUTES - 360',0,31,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (203,'256','POUTRES EN I - 256',0,29,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (204,'520','PRESTATIONS - 520',0,32,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (205,'525','PRESTATIONS VENTE DIRECTE - 525',0,32,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (206,'491','PROD.SPECIAUX AMENAG EXT. - 491',0,14,27);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (207,'502','PRODUITS SEMI-TRANSFORMES - 502',0,14,28);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (208,'293','PROF ACC CLINS LAS DETAIL - 293',0,9,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (209,'291','PROFIL ACCES CLINS DÉTAIL - 291',0,9,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (210,'446','RAB INDUS 2A - 446',0,34,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (211,'437','RAB INDUS ABJ - 437',0,34,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (212,'435','RAB INDUS ALLEMAND - 435',0,34,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (213,'413','RAB INDUS ANGER - 413',0,34,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (214,'424','RAB INDUS BCI - 424',0,34,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (215,'464','RAB INDUS BIO - 464',0,34,8);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (216,'432','RAB INDUS BURGER - 432',0,34,9);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (217,'440','RAB INDUS CHEVROLLIER - 440',0,34,10);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (218,'434','RAB INDUS CLAIRVAL - 434',0,34,11);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (219,'459','RAB INDUS CLAIRVAL_FINIS - 459',0,34,12);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (220,'461','RAB INDUS COUGNAUD - 461',0,34,13);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (221,'439','RAB INDUS DELTA BOIS - 439',0,34,14);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (222,'453','RAB INDUS ECMB - 453',0,34,15);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (223,'415','RAB INDUS EFISOL - 415',0,34,16);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (224,'462','RAB INDUS EMBALLAGE - 462',0,34,17);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (225,'454','RAB INDUS ERICA - 454',0,34,18);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (226,'417','RAB INDUS FINN EST - 417',0,34,19);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (227,'416','RAB INDUS FMI - 416',0,34,20);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (228,'444','RAB INDUS FOUSSIER - 444',0,34,21);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (229,'438','RAB INDUS FRANCE PORTE - 438',0,34,22);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (230,'419','RAB INDUS GERBOIS - 419',0,34,23);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (231,'426','RAB INDUS HOFFMAN - 426',0,34,24);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (232,'450','RAB INDUS ILE DE RE - 450',0,34,25);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (233,'448','RAB INDUS KNAUF - 448',0,34,26);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (234,'430','RAB INDUS LAHAYE - 430',0,34,27);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (235,'471','RAB INDUS LARIVIERE - 471',0,34,28);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (236,'451','RAB INDUS LATISSE - 451',0,34,29);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (237,'452','RAB INDUS LEMAN - 452',0,34,30);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (238,'421','RAB INDUS LITERIE PARIS. - 421',0,34,31);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (239,'443','RAB INDUS LOISIRS EQUIPEM - 443',0,34,32);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (240,'411','RAB INDUS MAISON BOIS - 411',0,34,33);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (241,'423','RAB INDUS MAM - 423',0,34,34);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (242,'445','RAB INDUS MBE - 445',0,34,35);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (243,'422','RAB INDUS MINCO - 422',0,34,36);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (244,'436','RAB INDUS MOBIL\'HOME - 436',0,34,37);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (245,'463','RAB INDUS MOBIL\'HOME B+F - 463',0,34,38);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (246,'473','RAB INDUS MOBIL\'HOME FINI - 473',0,34,39);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (247,'425','RAB INDUS NEFAB - 425',0,34,40);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (248,'460','RAB INDUS OSSATURE ILES - 460',0,34,41);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (249,'472','RAB INDUS PROCOPI - 472',0,34,42);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (250,'447','RAB INDUS RAPID\'HOME - 447',0,34,43);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (251,'427','RAB INDUS RAPIDO - 427',0,34,44);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (252,'420','RAB INDUS RENAULT - 420',0,34,45);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (253,'455','RAB INDUS ROESER - 455',0,34,46);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (254,'429','RAB INDUS SCAM - 429',0,34,47);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (255,'418','RAB INDUS SIMMONS - 418',0,34,48);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (256,'470','RAB INDUS SINBPLA - 470',0,34,49);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (257,'457','RAB INDUS SMD - 457',0,34,50);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (258,'458','RAB INDUS SMD_FINITION - 458',0,34,51);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (259,'441','RAB INDUS SNUB - 441',0,34,52);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (260,'428','RAB INDUS SOBOGAT - 428',0,34,53);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (261,'431','RAB INDUS SOCOPA - 431',0,34,54);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (262,'414','RAB INDUS SOMATEX - 414',0,34,55);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (263,'442','RAB INDUS SOTHOFERM - 442',0,34,56);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (264,'433','RAB INDUS UNILIN - 433',0,34,57);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (265,'380','RABOTÉS 4 FACES - 380',0,33,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (266,'407','RABOTES DIVERS DETAIL - 407',0,15,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (267,'449','RABOTES INDUSTR SOFOCO - 449',0,34,58);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (268,'517','REGULARISATION - 517',0,35,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (269,'404','RONDIN & PIQUET RESINEUX - 404',0,14,29);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (270,'405','RONDINS DETAIL - 405',0,15,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (271,'409','SAV MAISONNETTES - 409',0,14,30);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (272,'540','SHAKES & SHINGLES - 540',0,36,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (273,'243','SOLIVETTE (ARCHIVES) - 243',0,7,25);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (274,'238','STRUCTURE - CHEVRONS - 238',0,7,26);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (275,'237','STRUCTURE - SOLIVETTES - 237',0,7,27);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (276,'229','STRUCTURE FERMETTE CALIBR - 229',0,7,28);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (277,'561','TABLETTES LAMELLEES - 561',0,38,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (278,'560','TABLETTES LAMELLES - 560',0,37,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (279,'568','TABLETTES MASSIFS - 568',0,37,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (280,'569','TABLETTES MASSIVES - 569',0,38,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (281,'567','TABLETTES MELAMINEES - 567',0,38,4);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (282,'566','TABLETTES MELAMINES - 566',0,37,6);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (283,'570','TABLETTES POSTFORMES - 570',0,37,7);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (284,'376','TASS ET PLS BRUTS DÉTAIL - 376',0,39,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (285,'378','TASS ET PLS RABOTE DÉTAIL - 378',0,39,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (286,'370','TASSEAUX ET PLANCHES BRUT - 370',0,40,1);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (287,'372','TASSEAUX ET PLANCHES RABO - 372',0,40,2);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (288,'373','TASSEAUX ET PLS RABO FINI - 373',0,40,3);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (289,'246','TASSEAUX TRAPEZE - 246',0,7,29);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (290,'483','TERRASSES AUTRES ESSENCES - 483',0,14,31);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (291,'480','TERRASSES COMPOSITES - 480',0,14,32);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (292,'467','TERRASSES COMPOSITES GSB - 467',0,14,33);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (293,'400','TERRASSES EXOTIQUES - 400',0,14,34);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (294,'465','TERRASSES EXOTIQUES GSB - 465',0,14,35);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (295,'408','TERRASSES RESINEUX BRUTES - 408',0,14,36);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (296,'501','TERRASSES RESINEUX FINIES - 501',0,14,37);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (297,'513','TERRASSES RX BRUTES GSB - 513',0,14,38);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (298,'511','TERRASSES RX FINIES - GSB - 511',0,14,39);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (299,'530','TRANSPORTS - 530',0,41,0);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (300,'505','TRÉTEAUX - 505',0,1,5);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (301,'198','VOLIGES - 198',0,7,30);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (302,'242','VOLIGES - 242',0,7,31);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (303,'247','VOLIGES I - 247',0,7,32);
INSERT INTO `wa_sous_famille` (`id_sous_famille`,`CODE`,`LIBELLE`,`persistenceVersion`,`WA_famille_id_famille`,`listeWA_sous_famille_ORDER`) VALUES (304,'268','VOLIGES RABOTEES - 268',0,42,0);
